---
title: "Summary of Issues"
output: html_notebook
---

This document aims to provide R-scripts to calculate the Chesapeake Bay Phytoplankton indices described by [@lacouture_phytoplankton_2006]. In the [Validation] section of this document, an independent data source produced by Jacqueline M. Johnson is used QA/QC the processes outlined in this document. R functions developed to for metric scoring ([Metric Score Disagreement]), IBI scoring ([IBI Value Disagreement]), and IBI rating ([Rating Disagreement]) for the most part appear to be working correctly ([IBI Value, IBI Rating, Metric Scoring Disagreements]). However, before you dive into the documentation, I would like to direct your attention to a number of discrepancies that were identified in the [Metric Disagreement] section. The [Overview of Descrepancies] subsection is a good starting point because it summarizes the descrepancies by index, size of the descrepancy, metric, and data source. Some of these descrepancies are very small when metric values are compared and could be a result of round differences. To reduce the impact of minor changes metric scores are compared instead of metric values. Metric scores bin the data into four categories: 1, 3, 5, or NA. Therefore, if the metric score in this document differs from Jacqueline M. Johnson's metric score, the metric value has most likely changed quite a bit.


1. The metric with the greatest number of descrepancies is Pheophytin. 
    + This is an issue for all indices and both data sources.
        + MSU/Pearl Pheophytin values are incorrect more frequently.
    + Potential reason(s) for issue:
        + Calculation of mean pheophytin values.
            + Current procedure ([Prepare Water Quality Data]).
                + For oligohaline, mesohaline, and polyhaline indics water quality data is summarized and represented as the mean of the available samples collected from the surface layer and above the pycnocline layer.
                + For the freshwater index, water quality data is summarized as the mean value of all of the samples collected in the water column (i.e. collected from the surface, above pycnocline, below pycnocline, and benthic samples).
            + Jacqueline M. Johnson may have had a more complicated procedure then outlined in [Prepare Water Quality Data].
            + Additional data may have been acquired since the Jacqueline M. Johnson last calculated these values.

2. 

There are several probable sources for these discrepancies: 

1. The most likely source is an error or issue in this documents R-script. 
    + Typos
    + Incorrect interpretation of data preparation or calculation
    + Overlooked data preparation steps
    + Poorly documented data prepatration steps, which make it difficult for me to replicate

2. There is potential for issues in the Jacqueline M. Johnson's SQL code, which would ultimately lead to discrepancies between her calculated values and the values calculated in this document. 

3. The data may have been updated or altered between the time Jacqueline M. Johnson calculated the indices and now.
    + Taxonomic names may have been updated to reflect currently accepted taxonomic nomenclature.
    + Data could be represented differently in the new Chesapeake Bay Program CEDR database.

