---
title: "R Notebook"
output: html_document
---

```{r}
rank.counts <- bay.df %>% 
  summarize_if(is.character, funs(sum(!is.na(.)))) %>% 
  select(kingdom:ncol(.)) %>% 
  gather(rank, count, kingdom:ncol(.)) %>% 
  mutate(rank = factor(rank, levels = rev(rank))) %>% 
  filter(count != nrow(bay.df))
  
ggplot(rank.counts, aes(rank, count)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0))
```


```{r}
rank.counts.source <- bay.df %>% 
  group_by(source) %>% 
  summarize_if(is.character, funs(sum(!is.na(.)))) %>% 
  mutate(total = kingdom) %>% 
  #ungroup() %>% 
  select(source, total, kingdom:ncol(.)) %>% 
  gather(rank, count, kingdom:ncol(.)) %>% 
  mutate(rank = factor(rank, levels = rev(unique(rank))),
         pct = count / total * 100) %>% 
  filter(count != nrow(bay.df))
  
ggplot(rank.counts.source, aes(rank, count)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~source)


```

```{r}
ggplot(rank.counts.source, aes(rank, pct)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~source)
```


```{r}
bay.df <- bay.df %>% 
  group_by(unique_id) %>% 
  mutate(total = sum(reportingvalue)) %>% 
  ungroup()
```

```{r}
ggplot(bay.df, aes(source, total)) +
  geom_boxplot()
```

```{r}
ggplot(bay.df, aes(station, total)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
rich.df <- bay.df %>% 
  select(unique_id, station) %>% 
  distinct() %>% 
  mutate(kingdom = taxa_rich(bay.df, unique_id, reportingvalue, "kingdom"),
         class = taxa_rich(bay.df, unique_id, reportingvalue, "class"),
         order = taxa_rich(bay.df, unique_id, reportingvalue, "order"),
         family = taxa_rich(bay.df, unique_id, reportingvalue, "family"),
         genus = taxa_rich(bay.df, unique_id, reportingvalue, "genus"),
         species = taxa_rich(bay.df, unique_id, reportingvalue, "species")) %>% 
  gather(rank, rich, kingdom:species)

```

```{r}
ggplot(rich.df, aes())
```


```{r}
test <- bay.df %>% 
  dplyr::select(unique_id, layer, kingdom, reportingvalue) %>%
  group_by(layer, kingdom) %>% 
  summarize(count = sum(reportingvalue, na.rm = TRUE)) %>% 
  ungroup() %>% 
  spread(kingdom, count)

test[is.na(test)] <- 0
test <- as.data.frame(test)
row.names(test) <- test$layer
test <- test[, !names(test) %in% c("unique_id", "layer")]


dist.mat <- vegdist(test, method="jaccard")
plot(hclust(dist.mat))
```



```{r}
library(tidyverse)
test <- bay.df %>% 
  dplyr::select(unique_id, source, sampletype, sampledate, layer, gmethod,
         method, kingdom, reportingvalue) %>% 
  group_by_at(vars(-reportingvalue)) %>% 
  summarize(value = sum(reportingvalue, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(unique_id) %>% 
  mutate(total = sum(value, na.rm = TRUE),
         pct = value / total * 100, 
         count_id = n()) %>% 
  ungroup() %>% 
  group_by(source, kingdom, count_id) %>% 
  summarize(mean_pct = mean(pct, na.rm = TRUE) / unique(count_id))
  
ggplot(test, aes(source, mean_pct)) +
  geom_bar(aes(fill = kingdom), stat = "identity")
```


```{r}
test <- bay.df %>% 
  select(unique_id, source, sampletype, sampledate, layer, gmethod,
         method, kingdom:form) %>% 
  distinct()

library(vegan)
library(MASS)
data(varespec)
vare.dis <- vegdist(varespec)
plot(vare.dis)
vare.mds0 <- isoMDS(vare.dis)
```

```{r}
library(igraph) %>% invisible()
library(ggraph) %>% invisible()

taxa.df <- bay.df %>% 
  #head(1000) %>% 
  select(unique_id, source, kingdom, reportingvalue) %>% 
  group_by_at(vars(-reportingvalue)) %>% 
  summarize(reportingvalue = sum(reportingvalue, na.rm = TRUE)) %>% 
  ungroup() %>% 
  select(source, kingdom, reportingvalue) %>% 
  graph_from_data_frame()

taxa.df <- bay.df %>% 
  select(kingdom:form) %>% 
  distinct() %>% 
  graph_from_data_frame()

taxa.df <- as.dendrogram(hclust(dist(taxa.df)))
ggraph(taxa.df) +
 geom_edge_elbow2(aes(colour = kingdom))
  
set.seed(2017)
ggraph(taxa.df) +
  
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)
  
  data(iris)
  
  
  dendrogram <- as.dendrogram(hclust(dist(iris[, 1:4])))
```




```{r}
library(vegan) %>% 
  invisible()

table(bay.df$method)
wide.df <- bay.df %>% 
  dplyr::select(unique_id, source, sampletype, sampledate, layer,
         method, kingdom, reportingvalue) %>% 
  group_by_at(vars(-reportingvalue)) %>% 
  summarize(reportingvalue = sum(reportingvalue, na.rm = TRUE)) %>% 
  ungroup() %>% 
  spread(kingdom, reportingvalue)

taxa.matrix <- wide.df %>% 
  dplyr::select(-unique_id, -source, -sampletype, -sampledate, -layer, -method)
taxa.matrix[is.na(taxa.matrix)] <- 0


nmds <- metaMDS(head(taxa.matrix, 1000), k = 3)
plot(nmds, dis = "sp", type = "n") #, xlim = c(-1,1), ylim = c(-0.8, 0.8)) 
points(nmds, display = "sites", cex = 0.8, pch=22)
ordiellipse(nmds, gen.df$year, kind = "sd", conf=0.95,
            draw = "polygon", col = gen.df$color, label = TRUE)
ordihull(nmds, gen.df$year, display="sites", draw = "polygon", col=gen.df$color, label=TRUE)
```

